-- logins sql
USE [master]
GO
CREATE LOGIN [Admin] WITH PASSWORD=N'Pa$$w0rd', DEFAULT_DATABASE=[ProjetoBD2], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

USE [master]
GO
CREATE LOGIN [Cliente] WITH PASSWORD=N'Pa$$w0rd', DEFAULT_DATABASE=[ProjetoBD2], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

USE [master]
GO
CREATE LOGIN [Insert_Data_User] WITH PASSWORD=N'Pa$$w0rd', DEFAULT_DATABASE=[ProjetoBD2], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

USE [master]
GO
CREATE LOGIN [Select_Data_Userr] WITH PASSWORD=N'Pa$$w0rd', DEFAULT_DATABASE=[ProjetoBD2], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO

-- logins windows
USE [master]
GO
CREATE LOGIN [BD2\ADMIN] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO

USE [master]
GO
CREATE LOGIN [BD2\Admin_InsertData] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO

USE [master]
GO
CREATE LOGIN [BD2\Admin_Only_Select] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO

USE [master]
GO
CREATE LOGIN [BD2\User1] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO

USE [master]
GO
CREATE LOGIN [BD2\User2] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO

USE [master]
GO
CREATE LOGIN [BD2\User3] FROM WINDOWS WITH DEFAULT_DATABASE=[ProjetoBD2]
GO
